// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGsAj_gcubt9TEzHyctCRb7n22jZqKEV8',
    appId: '1:630443648315:web:e4fbeb35346466c69c431e',
    messagingSenderId: '630443648315',
    projectId: 'portfolio-d3d7d',
    authDomain: 'portfolio-d3d7d.firebaseapp.com',
    storageBucket: 'portfolio-d3d7d.appspot.com',
    measurementId: 'G-102LZEQ2QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk1Qn2GoEmYUX75JeN8iYBqqaS4jwin14',
    appId: '1:630443648315:android:3195d22488b206719c431e',
    messagingSenderId: '630443648315',
    projectId: 'portfolio-d3d7d',
    storageBucket: 'portfolio-d3d7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6I7DhcXHEokTfhNtyfbXKaFWMqlA-J9w',
    appId: '1:630443648315:ios:9208d0c63997f50e9c431e',
    messagingSenderId: '630443648315',
    projectId: 'portfolio-d3d7d',
    storageBucket: 'portfolio-d3d7d.appspot.com',
    iosBundleId: 'com.example.protfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6I7DhcXHEokTfhNtyfbXKaFWMqlA-J9w',
    appId: '1:630443648315:ios:9208d0c63997f50e9c431e',
    messagingSenderId: '630443648315',
    projectId: 'portfolio-d3d7d',
    storageBucket: 'portfolio-d3d7d.appspot.com',
    iosBundleId: 'com.example.protfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGsAj_gcubt9TEzHyctCRb7n22jZqKEV8',
    appId: '1:630443648315:web:a2ae81b66d86c7da9c431e',
    messagingSenderId: '630443648315',
    projectId: 'portfolio-d3d7d',
    authDomain: 'portfolio-d3d7d.firebaseapp.com',
    storageBucket: 'portfolio-d3d7d.appspot.com',
    measurementId: 'G-Y5FKY0NKR3',
  );
}
